### PR TITLE
Should report only error & warning typed messages by default

### LINKED ISSUE #30: Should report all but dependency typed messages by default
Related to https://github.com/TrySound/postcss-inline-svg/issues/32

I guess this is related to how messages are filtered by default [here](https://github.com/postcss/postcss-reporter/blob/24518056bcaebbd6252fecfdfa0ccca158a54797/lib/reporter.js#L32)?

### PR DESCRIPTION
**Pull request by shouze**
Fixes #30, related to TrySound/postcss-inline-svg#32.

### CODE REVIEW

**Comment by davidtheclark** [comment]
I don't understand why `message.type !== 'dependency'` is a sufficient filter. Isn't the goal to filter out non-warning messages by default, so `message.type === 'warning'`?

The PostCSS API example for creating a message suggests that the `type` property is arbitrary, and I don't see anything stating that `type: 'dependency'` is a normal, reliable pattern.

screen shot 2016-11-06 at 3 42 27 pm

**Comment by shouze** [comment]
Indeed, maybe `warnings` AND `errors` should be accepted by default as in tests we have samples with `warnings` & `errors`? I've updated the PR in this direction.

I can reduce to warnings too, I just wonder how far it would `break` modules that uses this reporter.
If errors are required too, maybe the postcss documentation would deserve to be updated too?

**Comment by davidtheclark** [comment]
@shouze I don't think `type: "error"` is a standard part of the PostCSS API. I think the only standard type is `"warning"`. @ai is that correct?

**Comment by shouze** [comment]
Ok so I restrict to `warning` only in this case. I will have to change other tests of the suite as they will break if I filter only on `warning` (all the `error` ones, 4 failures to fix).

**Comment by shouze** [comment]
ping @davidtheclark @ai ok I've amended the commit and filter only warnings by default guys.

**Comment by davidtheclark** [comment]
Thanks @shouze.

**Pull request merged**
