### PR TITLE
Better styling for the output

### PR DESCRIPTION
**Pull request by onigoetz**
Inspired from eslint's formatter, here is a pull request for a nicer formatting.

The changes are : 
- Show icons for errors as well.
- use `text-table` to show the output in a tabular way, mainly to align the plugin name
- the `noIcon` option now writes `error` or `warning`
- line numbers are centered on the colon

### CODE REVIEW

**Comment by davidtheclark** [comment]
Thanks a lot for the contribution, @onigoetz! Looks like a nice improvements, and a really good PR (thanks for attending to the tests!). But it's also a big one, so I will need to look it over when I have a little more time and concentration --- within the next few days for sure.

One quick comment about the screenshot you provided: I'm not sure that's how errors vs warnings will work out for this, because PostCSS "errors" are really CSS syntax errors, not messages with a severity level "warning" that any old plugin can throw in at whim (is that right, @ai?). I still think the visual distinction you worked on is great; I just think that it may not end up differentiating stylelint complaints as your screenshot indicates.

One more comment comes to mind: One thing that I *don't* especially like about the ESLint reporter format is the dull gray of the line/column positions. To me that position is very important information and I definitely want to see it. Do you want to experiment with a brighter display for those positions?

**Comment by onigoetz** [comment]
Thanks.

I just discovered (with your comment on stylelint/stylelint#842) that postcss warnings are just. So that was done prior to this new knowledge.

( for ulterior reference: https://github.com/postcss/postcss/blob/master/docs/api.md#warning-class )

So, what I was thinking is : if we get a `type` parameter, we write it, if not, we just set as warning

Now the question is, what key should we look for when checking for severity ? because stylelint sets `severity`

and for the moment, `postcss-reporter` checks for `type` (that's what I was reporting in  stylelint/stylelint#842)

I agree that the colors aren't great, I will try with other colors.

Also, that's not a problem if the Pull Request isn't merged today, take your time to review it.

**Comment by onigoetz** [comment]
So, I improved the readability and handled the severity differently, everything is a warning by default. 

If type provides "info" or "error" it will use them, everything else will fall back to warning

**Comment by davidtheclark** [comment]
@postcss/owners How do you feel about these changes, especially the severity level suggestions?

@onigoetz What happens with this tabular layout if one of the message is multiple lines and the others are not? What does it look like?

**Comment by ben-eb** [comment]
Looks good to me. :+1:

**Comment by onigoetz** [comment]
@davidtheclark thanks for pointing that out, I didn't think about that and... it was very ugly ... I changed the table library to add proper line wrapping.

Here's a screenshot : 
wrapped_text

**Comment by davidtheclark** [comment]
@onigoetz, Nice job! I'm glad you could pull that off.

**Comment by davidtheclark** [comment]
@onigoetz I am not sure that introducing special treatment of a `severity` property is appropriate for this module. I think this module needs to be completely independent of any particular plugin, and paying attention to a `severity` property is specific treatment for stylelint. If it's not a part of the standard PostCSS API, I feel like probably postcss-reporter should do nothing with it. @ai do you agree? 

Otherwise I think everything's good. Just want to further discuss that one point.

**Comment by onigoetz** [comment]
@davidtheclark I have to disagree on this one.

Despite what the attached screenshot lets think, all reports generated by stylelint are marked as warnings, as I reported in stylelint/stylelint#842

That's because `postcss-reporter` reads the `type` property and stylelint sets the `severity` property : 

- Postcss-reporter reads `type` : https://github.com/postcss/postcss-reporter/blob/master/lib/formatter.js#L64
- Postcss sets `type`: https://github.com/postcss/postcss/blob/master/lib/warning.es6#L3
- Stylelint sets `severity`: https://github.com/stylelint/stylelint/blob/master/src/utils/report.js#L73

The special treatment of warnings was already here before, it was just improved a bit.

**Comment by davidtheclark** [comment]
OK maybe I misunderstood. I'll just take a real close look and try to merge this weekend. Sorry for the delay --- have had a lot of sudden stuff happening.

**Comment by davidtheclark** [comment]
After looking at the code I still think the treatment of `type` isn't quite right.

PostCSS messages [are expected](https://github.com/postcss/postcss/blob/master/docs/api.md#resultmessages) to have an *arbitrary* type property. You are treating *type* as equivalent to severity, but I think that's an assumption this module shouldn't make. (The example of `type` in the PostCSS docs have a value of `'min-browser'`.) PostCSS *errors* (CssSyntaxErrors) are not delivered as messages and therefore not displayed by postcss-reporter. So really I think there is just one standardized distinction in messages: `type: warning`, and `type: [anything else]` (@ai correct me if I'm wrong). Unless the PostCSS API introduces other standard distinctions I don't think postcss-reporter should.

So I'm thinking the main idea we should keep here is the tabular layout. We could also retain the count thing, but it would be more generic: just communicating the total number of messages, and the number of those messages that are warnings.

At the same time, though, I'm also a little concerned about the tabular layout and wonder if that should be a separate formatter instead of the standard one. In your example the terminal window is wide and all the plugins are "stylelint" --- but what if the terminal window is more narrow and some of the plugins have pretty long names? Does it still look better than if the plugin is just appended to the end of the line? If so, maybe the table should just have two columns: position and message/plugin?

**Comment by onigoetz** [comment]
Sorry for the delay, I was very busy on other projects, I have a bit more time to come back to this now.

Okay, I understand your point about the warnings, in that case, can we just say : 
- warning shows a warning icon
- error shows a cross
- anything else just shows nothing ?

This is similar to what we have today, just with the added error. What do you think ?

**Comment by davidtheclark** [comment]
But what is the "error" -- where does that come from? If it's a CssSyntaxError it is thrown like a regular error and will break the process --- we won't make it to postcss-reporter. If it's `severity: error` on a PostCSS "warning", that's a stylelint-specific construct again.

Warnings already show the warning icon.

So I'm not sure there's anything to change here. @onigoetz is that right? I think that your intended improvements are excellent but they are specific to stylelint --- and I totally agree that we need a better solution for stylelint than to rely on postcss-reporter. There's an issue about it, https://github.com/stylelint/stylelint/issues/917, and I'd really appreciate your input and initiative over there.

**Comment by onigoetz** [comment]
As you said:

> So really I think there is just one standardized distinction in messages: `type: warning`, and `type: [anything else]`

You're right the icon for the moment is warning, my proposition is to add an icon for error (to be nice to the user) we're not inventing a standard, we just have an icon for error and we know that if the user gets `type: error` ... probably it's an error. So why not just show it as it is? 

The standard is already quite open (you can set warning or anything else).

And this change would, again, not be Stylelint specific, as Stylelint sets the `severity` not the `type`

**Comment by davidtheclark** [comment]
My thinking is that it's not a PostCSS standard to use `type: error`, so this particular reporter shouldn't treat it as something special. If you want to register an error in a PostCSS plugin, you should probably use a CssSyntaxError. What I mean is we shouldn't build this tool around `type: error` any more than we should `type: alert` or `type: blergh`. The only `type` that is standard is `warning`.

**Comment by davidtheclark** [comment]
@onigoetz I suggest you take the awesome styling work you've done here over to the stylelint repo and make a PR for a new text reporter for stylelint. stylelint could drop its use of postcss-reporter's standard formatter and use the better-styled alternative you've made. Then gulp users could switch to [gulp-stylelint](https://github.com/olegskl/gulp-stylelint) to use that superior reporter.

**Comment by onigoetz** [comment]
So should I make my PR to `stylelint` or `gulp-stylelint` ?

And should it consume the messages from other gulp plugins ? It seems to me that would violate the single responsibility principle.

Maybe that would be an occasion to finish `postcss-stylelint-reporter` ?

**Comment by davidtheclark** [comment]
I'm thinking a PR to stylelint to modify its text reporter. gulp-stylelint uses stylelint's built-in reporters now. Keep in mind that stylelint's text reporter now has a `--verbose` option to take into account.

> should it consume the messages from other postcss plugins 

No, stylelint reporters are stylelint-specific.

> Maybe that would be an occasion to finish postcss-stylelint-reporter ?

I'm actually thinking that postcss-stylelint-reporter should be destroyed because it won't work. Because of this: https://github.com/postcss/postcss/issues/774

**Pull request closed without merging**
