### PR TITLE
Custom filter function

### PR DESCRIPTION
**Pull request by texastoland**
See [`README`](https://github.com/jane/postcss-reporter/blob/custom-filter-function/README.md#options).

### CODE REVIEW

**Comment by texastoland** [comment]
The failing test is in unrelated code:

```
# defaultFormatter with real sourcemaps
/home/travis/build/postcss/postcss-reporter/node_modules/postcss/lib/previous-map.js:91
                throw new Error('Unsupported previous source map format: ' + p
                      ^
Error: Unsupported previous source map format: {"version":3,"sources":["file.original.css"],"names":[],"mappings":";OAqG2G","file":"file.css"}
```

Any ideas?

**Comment by texastoland** [comment]
Based on #29 it appears the failure was introduced by a dependency of `source-maps` not this change.

**Comment by texastoland** [comment]
Hmm WebPack itself still prints the unreported messages 😓 I understand why that would be but not quite what I intended.

**Comment by davidtheclark** [comment]
> Hmmm WebPack itself still prints the unreported messages 😓 I understand why but not what I intended. I decided to use sequential reporters instead:

@texastoland I don't quite understand: why aren't you satisfied with the functionality your PR contains?

**Comment by davidtheclark** [comment]
@texastoland I ask because I think it's a good addition, and was just about to merge and release. 👍

**Comment by texastoland** [comment]
My exact use case was to sequence `css-variables` after `custom-properties` (bundled with `cssnext`) until I can submit a patch to the former. The latter correctly warns about unsupported behavior that I intended to silence. Its warnings still get rendered by WebPack itself instead of `reporter` however. My workaround was a `formatter` that outputs nothing. I think my user case is unique and not worth supporting. I'm happy with the changes in this PR however 👍

**Comment by davidtheclark** [comment]
In v1.4.1 I released this functionality, but split the filter function into its own option. Thanks again!

**Comment by texastoland** [comment]
The reason I didn't split it into its own function is because it would be somewhat confusing to provide both but perhaps it's the lesser of two evils 👌

**Comment by davidtheclark** [comment]
I thought it made sense because we're not always filtering by plugin name with that function. In your example, for instance, you're filtering by message type. So it seemed better to me not to have it in a `filter` rather than a `plugins` option.

**Comment by texastoland** [comment]
The difficulty becomes whether to `&&` or `||` the results. Note in the case of negation I did neither because the truth tables don't work out. I think (not strongly) it'd be easier to just reimplement name checking in a function.

**Comment by texastoland** [comment]
Using it after all 🙏

**Pull request merged**
