### PR TITLE
Fix tests on windows

### PR DESCRIPTION
**Pull request by TrySound**
/cc @davidtheclark

### CODE REVIEW

**Comment by davidtheclark** [comment]
Thanks.

**Comment by TrySound** [comment]
@davidtheclark Patch release?

**Comment by davidtheclark** [comment]
Oh, it didn't register to me that this was attached to an active bug. I thought it was just setting up appveyor. I will release, yes.

**Comment by TrySound** [comment]
@davidtheclark It's not big bug. But forward slash looks much nicer.

**Pull request merged**
